### PR TITLE
Make gevent optional

### PR DESCRIPTION
**Pull request by OzzieIsaacs**
Still not 100% happy.
Could you please make the gevent server and gdrive part optional. So if somebody doesn't want wot use it, he doesn't have to install the dependencys.
I started to do it, so it runs (almost) without it.
I got this error if I don't have a app.db already:
Traceback (most recent call last):
  File "C:\Program Files (x86)\PyCharm Community Edition\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\PyCharm Community Edition\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/Desktop/calibre-web_jack_ozzie/cps.py", line 13, in <module>
    from cps import web
  File "D:/Desktop/calibre-web_jack_ozzie\cps\web.py", line 18, in <module>
    import ub
  File "D:/Desktop/calibre-web_jack_ozzie\cps\ub.py", line 539, in <module>
    config = Config()
  File "D:/Desktop/calibre-web_jack_ozzie\cps\ub.py", line 292, in __init__
    self.loadSettings()
  File "D:/Desktop/calibre-web_jack_ozzie\cps\ub.py", line 318, in loadSettings
    if (self.config_calibre_dir is not None and not self.config_use_google_drive) or os.path.exists(self.config_calibre_dir + '/metadata.db'):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Could you please fix this.

2nd wish, before I broke it, I saw if you tick the use gdrive checkbox (which look fine now, btw.) the gdrive stuff apears, but the normal drive doesn't disappear. Could you please implement this.
(we are getting closer..) 
Thanks again for the great work.

### CODE REVIEW

**Comment by 89jd** [comment]
Hi,

Thanks for this, helps a lot. Just to confirm, the remaining tasks after merging these changes are:

1. Merge this pull request
2. Fix issue if metadata.db doesn't exist
3. The path you select is actually used. If you use google drive mode, it uses this folder as the location of metadata.db and where to temporary upload files to before uploading on to google drive

**Review by 89jd — CHANGES_REQUESTED** [review]
Can you just do one change for me please?

You have moved update_dir_structure_gdrive to gdriveutils, I think this will fail, as gdriveutils needs imports for db and get_valid_filename

**Review by 89jd — CHANGES_REQUESTED** [review]
Hi,

Also, these changes will break the updated, web needs a reference to the http_server, so that I can tell it to restart from the updater, this is why I moved the start_gevent method to web, so helper can access it. If you have another way of restarting, that would also be fine.

Thanks

Jack

**Comment by OzzieIsaacs** [comment]
You can revert my changes, I quickly tried to make gevent optional, and after I few changes I stuck with the metadata problem. 
Regarding 3. okay, didn't have chance to test it.
Afterwards I hope there arise no new problems, and than I'm merging it

**Pull request closed without merging**
